Repository rakutentech/js-miniapp, pull requests merged in 2022-02, with the labels that each got.

#189 [MINI-4694] download files to device
  js-miniapp-bridge/src/common-bridge.ts
  js-miniapp-bridge/src/index.ts
  js-miniapp-bridge/src/types/download-file-headers.ts
  js-miniapp-bridge/test/test.spec.ts
  js-miniapp-sample/src/pages/file-download.js
  js-miniapp-sample/src/services/filedownload/actions.js
  js-miniapp-sample/src/services/filedownload/reducers.js
  js-miniapp-sample/src/services/filedownload/types.js
  js-miniapp-sample/src/services/reducers.js
  js-miniapp-sdk/src/index.ts
  js-miniapp-sdk/src/miniapp.ts
  js-miniapp-sdk/test/miniapp.spec.ts
Labels: enhancement

#182 [MINI-1733] Feat/purchase item
  js-miniapp-bridge/src/common-bridge.ts
  js-miniapp-bridge/src/index.ts
  js-miniapp-bridge/src/types/purchaseProduct.ts
  js-miniapp-sample/src/pages/purchase.js
  js-miniapp-sample/src/routes.js
  js-miniapp-sdk/src/index.ts
  js-miniapp-sdk/src/miniapp.ts
  js-miniapp-sdk/src/modules/purchase-item.ts
Labels: sample-app, SDK

#192 [MINI-4694] download files to device fix
  js-miniapp-sample/src/pages/file-download.js
Labels: bug
